### ISSUE TITLE
Relations' repository bindings are broken after first time access 

### ISSUE THREAD

**Issue by shazha** [strongloop/loopback-next#2495]
I'm running the official to-do-list example against the latest loopback4 packages, and the following error is thrown when I tried to access `GET /todo-lists/1/todos`:
```
Unhandled error in GET /todo-lists/1/todos: 500 Error: The key repositories.TodoRepository was not bound to any value.
    at RequestContext.getBinding (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/context/dist/context.js:493:15)
    at RequestContext.getValueOrPromise (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/context/dist/context.js:528:30)
    at RequestContext.get (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/context/dist/context.js:471:27)
    at DefaultHasManyRepository.getter [as getTargetRepository] (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/context/dist/inject.js:171:20)
    at DefaultHasManyRepository.find (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/repository/dist/relations/has-many/has-many.repository.js:24:45)
    at TodoListTodoController.find (/Users/shazha/github/loopback-next/examples/todo-list/dist/controllers/todo-list-todo.controller.js:31:50)
    at value_promise_1.transformValueOrPromise.args (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/context/dist/resolver.js:177:41)
    at Object.transformValueOrPromise (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/context/dist/value-promise.js:231:16)
    at Object.invokeMethod (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/context/dist/resolver.js:172:28)
    at ControllerRoute.invokeHandler (/Users/shazha/github/loopback-next/examples/todo-list/node_modules/@loopback/rest/dist/router/controller-route.js:65:32)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
```
It seems  repository bindings for all relations, including HasOne/HasMany/BelongsTo, are broken after I upgraded my loopback4 packages to the latest release.

**Comment by jeckel** [comment]
I just reproduced the same issue after upgrading loopback4

**Comment by apocaliss92** [comment]
Same here, updated all the packages and got the same error (complains about hasMany relation)

**Comment by dhmlau** [comment]
I'm able to reproduce it with the latest versions.  The issue seems to be coming from the `@loopback/context`.  As a temp workaround,  use `"@loopback/context": "1.5.1"` instead of the latest. 
@raymondfeng, it might be related to [this commit](https://github.com/strongloop/loopback-next/commit/e5e5fc4).

**Comment by raymondfeng** [comment]
It might be related to https://github.com/strongloop/loopback-next/blob/e5e5fc4c89b0e9d2a9e3e4d9604ad438ff54566d/packages/rest/src/request-context.ts#L24-L26

**Comment by raymondfeng** [comment]
The issue has been there but it was surfaced by https://github.com/strongloop/loopback-next/blob/e5e5fc4c89b0e9d2a9e3e4d9604ad438ff54566d/packages/rest/src/request-context.ts#L24-L26. Here is the causes:

1. The `ControllerRoute` binds `controllerFactory` as a singleton. It's wrong.
2. The Repository is a singleton but it has an injected getter function, which internally references the `request context` that triggers the creation.
3. After the `request context` closes, the getter function stops working.

**Comment by raymondfeng** [comment]
It's now fixed by https://github.com/strongloop/loopback-next/pull/2513. Please upgrade to latest release and verify.

**Comment by issahh89** [comment]
i was just going through the Loopback4 todo list tutorial and did all the steps but when tried out one of the endpoint i got the same error

```
Unhandled error in GET /todos?filter=%7B%0A%20%20%22offset%22%3A%200%2C%0A%20%20%22limit%22%3A%20100%2C%0A%20%20%22skip%22%3A%200%2C%0A%20%20%22order%22%3A%20%5B%0A%20%20%20%20%22string%22%0A%20%20%5D%2C%0A%20%20%22where%22%3A%20%7B%0A%20%20%20%20%22additionalProp1%22%3A%20%7B%7D%0A%20%20%7D%2C%0A%20%20%22fields%22%3A%20%7B%0A%20%20%20%20%22id%22%3A%20true%2C%0A%20%20%20%20%22title%22%3A%20true%2C%0A%20%20%20%20%22desc%22%3A%20true%2C%0A%20%20%20%20%22isComplete%22%3A%20true%0A%20%20%7D%0A%7D: 500 Error: The key 'repositories.TodoRepository' is not bound to any value in context TodoListApplication-05dcdbd9-f58e-47ab-9bc0-c0f3c0ff7345
    at TodoListApplication.getBinding (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/context.ts:738:11)
    at RestServer.getBinding (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/context.ts:734:27)
    at RequestContext.getBinding (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/context.ts:734:27)
    at RequestContext.getValueOrPromise (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/context.ts:802:26)
    at /Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/resolver.ts:155:20
    at /Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/resolution-session.ts:149:13
    at Object.tryWithFinally (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/value-promise.ts:196:14)
    at Function.runWithInjection (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/resolution-session.ts:148:12)
    at resolve (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/resolver.ts:139:38)
    at /Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/resolver.ts:241:12
    at Object.resolveList (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/value-promise.ts:168:28)
    at resolveInjectedArguments (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/resolver.ts:220:10)
    at Object.instantiateClass (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/resolver.ts:58:25)
    at /Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/binding.ts:578:29
    at Binding._getValue (/Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/binding.ts:454:14)
    at /Users/issahaddadin/Sites/todo-list/node_modules/@loopback/context/src/binding.ts:338:23
```

i'm really a beginner in here, but it seems this issue is back.

**Comment by dougal83** [comment]
Hi @issahh89  There is not enough info to help. Could you make a new issue and post a public repo to on GitHub to enable someone to take a deeper look at the issue?

For future reference, you can link to relevant issues like this one from elsewhere by using the issue number `#2495` (without quotes) in your comment.
